; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	zeed/ESP Async WebServer@^1.2.3
	adafruit/DHT sensor library@^1.4.7
	adafruit/Adafruit MPL3115A2 Library@^2.1.2
	miguel5612/MQUnifiedsensor@^3.0.5
